### ISSUE TITLE
Wrong sha

### ISSUE THREAD

**Issue by jagajaga** [MarcWeber/vim-addon-vim2nix#1]
Seems that we have to do `nix-prefetch-git` two times.
Because with `--leave-dotGit` produses different sha rather then without it.
But without `--leave-dotGit` we can't get the commit's date.
https://github.com/MarcWeber/vim-addon-vim2nix/blob/master/autoload/nix.vim#L47 Here
For example:

```
$ nix-prefetch-git --leave-dotGit --url  https://github.com/kien/ctrlp.vim
git revision is b5d3fe66a58a13d2ff8b6391f4387608496a030f
hash is 3736b2f152df20be0a0d5ed6a39929b2df1ed9bbe98f68d80db657c00f0dcb30
$ nix-prefetch-git --url  https://github.com/kien/ctrlp.vim 
git revision is b5d3fe66a58a13d2ff8b6391f4387608496a030f
hash is 41f7884973770552395b96f8693da70999dc815462d4018c560d3ff6be462e76
```

And the last one is the correct one for `Nix` to accept.

**Comment by MarcWeber** [comment]
You can also discuss patching nix-prefetch-git to output the date along with the hash

**Comment by jagajaga** [comment]
https://github.com/NixOS/nixpkgs/issues/6479

**Comment by jagajaga** [comment]
Check https://github.com/NixOS/nixpkgs/pull/6522 please.

**Comment by jagajaga** [comment]
Check this https://github.com/NixOS/nixpkgs/commit/06f5651ef59b75996f782519daf96898fa85cfc6

**Comment by jagajaga** [comment]
ping

**Comment by MarcWeber** [comment]
I submitted working code - if you want a change send a PR or pay me. If you want me to make send you an offer let me know - my time is limited and other things are more important to me. Thanks for caring about this plugin. If you want to become a contributor you should be able provide a fix or ask more specific questions than ping - I'm sure you're skilled enough to do so :) cu

**Comment by jagajaga** [comment]
Sorry, I really was not polite. And I really could do it by myself... Next 
time gonna turn my brain on :)
Thank you once again!
